### ISSUE TITLE
联表查询问题

### ISSUE THREAD

**Issue by ymind** [kotlin-orm/ktorm#221]
情况1：

```kotlin
val q = database.sequenceOf(Employees).query.where { Employees.department.id.greater(0) }

// 生成SQL（结果正确）
SELECT `t_employee`.`id` AS `t_employee_id`, `t_employee`.`name` AS `t_employee_name`, `t_employee`.`job` AS `t_employee_job`, `t_employee`.`manager_id` AS `t_employee_manager_id`, `t_employee`.`hire_date` AS `t_employee_hire_date`, `t_employee`.`salary` AS `t_employee_salary`, `t_employee`.`department_id` AS `t_employee_department_id`, `_ref0`.`id` AS `_ref0_id`, `_ref0`.`name` AS `_ref0_name`, `_ref0`.`location` AS `_ref0_location`, `_ref0`.`mixedCase` AS `_ref0_mixedCase` 
FROM `t_employee` 
LEFT JOIN `t_department` `_ref0` ON `t_employee`.`department_id` = `_ref0`.`id` 
WHERE `_ref0`.`id` > ? 
```

情况2：

```kotlin
val q = database.from(Employees).select().where { Employees.department.id.greater(0) }

// 生成SQL（未能自动联表）
SELECT * 
FROM `t_employee` 
WHERE `_ref0`.`id` > ? 
```

情况3：

```kotlin
val q = database.from(Employees)
    .leftJoin(Departments, on = Departments.id.eq(Employees.departmentId)) // 错误引用
    .select()
    .where { Employees.department.id.greater(0) }

// 生成SQL（有联表，表别名错误）
SELECT * 
FROM `t_employee` 
LEFT JOIN `t_department` ON `t_department`.`id` = `t_employee`.`department_id`
WHERE `_ref0`.`id` > ? 
```

情况4：

```kotlin
val q = database.from(Employees)
    .leftJoin(Employees.department, on = Employees.department.id.eq(Employees.departmentId)) // 正确引用
    .select()
    .where { Employees.department.id.greater(0) }

// 生成SQL（有联表，结果正确）
SELECT * 
FROM `t_employee` 
LEFT JOIN `t_department` `_ref0` ON `_ref0`.`id` = `t_employee`.`department_id` 
WHERE `_ref0`.`id` > ? 
```

**总结如下：**
1. 情况1、情况4为正确使用ktorm，其中情况4的写法在官网似乎没有例子；
2. 情况3为错误使用实例，但我认为大多数人依靠直觉会去尝试这么写；
3. 情况2与情况1相似，作为新手我直觉上就这么尝试了；

**想法和建议**
1. 如果可能，建议增加对情况2的支持；
2. 针对易混淆的语法，建议完善文档。如果可能，建议屏蔽这些不规范的写法；

**Comment by vincentlauvlwj** [comment]
> 情况1、情况4为正确使用ktorm，其中情况4的写法在官网似乎没有例子

不，这些情况都不是我们的推荐写法，4 可以勉强算是正确的，要找例子的话，官网有一个类似的 https://www.ktorm.org/zh-cn/entity-finding.html#joinReferencesAndSelect

> 情况3为错误使用实例，但我认为大多数人依靠直觉会去尝试这么写

调用 `leftJoin` 函数的时候，直接联的就是 `Departments`，所以我觉得大部分人在下面调用 `where` 的时候，会这样写 `where { Departments.id.greater(0) }`，而不是突然换成 `Employees.department`，因为这完全就是另一个表对象，你觉得呢？

> 情况2与情况1相似，作为新手我直觉上就这么尝试了

`from` 函数是使用 SQL DSL 的入口，SQL DSL 是不会自动联表的，所以在 `where` 中莫名其妙地出现另一个表对象自然是不行的。我不知道你为什么会这么写，是被哪里的文档误导了吗，可以指出来，我去改改

> 如果可能，建议增加对情况2的支持

不，刚刚说了，SQL DSL 是不会自动联表的，想自动联表，应该用 `sequenceOf`

> 针对易混淆的语法，建议完善文档

我觉得文档已经写得很清楚了，你举的这几个例子从来就没在文档里面出现过 😂 如果是被哪里误导了，我可以去改改

> 如果可能，建议屏蔽这些不规范的写法

同意，后面会优化，屏蔽掉不规范的写法

**Comment by ymind** [comment]
感谢解惑！

这一切来源于一个想法，我关注ktorm时间不长，但它很吸引我，所以这两天开始研究如何使用（还没有完全阅读和理解文档及源码）。

由于之前我针对 QueryDsl 做过一个 rsql 语法封装（见：https://github.com/ymind/rsql-querydsl ），所以也想试试ktorm是否能够适配（学习），在适配过程中遇到了问题便开始各种尝试。

我编写了一个 `rsql-ktorm` 的原型代码（完成后会推到Github），基本功能已经实现，它的作用举例如下：

```sql
-- 假设我输入了如下rsql语句：
-- rsql = "name!=bob and (name==alice or id=in=(2,3,4,5)) or manager_id>0 and hire_date=before=2099-12-31"

-- 经过 `rsql-ktorm` 转换后将生成如下查询：
SELECT * 
FROM `t_employee` 
LEFT JOIN `t_department` `_ref0` ON `_ref0`.`id` = `t_employee`.`department_id` 
WHERE ((`t_employee`.`name` <> ?) AND ((`t_employee`.`name` = ?) OR (`t_employee`.`id` IN (?, ?, ?, ?)))) OR ((`t_employee`.`manager_id` > ?) AND (`t_employee`.`hire_date` < ?)) 
ORDER BY `t_employee`.`department_id` DESC, `t_employee`.`name`
```

这部分功能已经基本实现完成，但昨天开始在尝试解决联表查询的时候遇到了大麻烦，所以才进行了上述各种各样的尝试来了解ktorm的相关实现逻辑。

下面是一个蹩脚的例子：
```kotlin
val rsqlDslBuilder = RsqlDslBuilder(
    database.from(Employees)
        .leftJoin(Employees.department, on = Employees.department.id.eq(Employees.departmentId)),
    // Employees.id,
    // Employees.name,
    // Employees.departmentId,
    // Departments.name,
)
val rsqlExpressionVisitor = RsqlExpressionVisitor(rsqlDslBuilder)

// val rsql = "name!=bob and (name==alice or id=in=(2,3,4,5)) or manager_id>0 and hire_date=before=2099-12-31"
val rsql = "name!=bob and (name==alice or id=in=(2,3,4,5)) or manager_id>0 and hire_date=before=2099-12-31 or department_id.id>0"

val operators = RsqlUtil.getOperators()
val rootNode = RSQLParser(operators).parse(rsql)
val predicate = rootNode.accept(rsqlExpressionVisitor)

val q = rsqlDslBuilder.query
    .whereWithConditions {
        // it += Employees.job.isNotNull()
        // it += Employees.department.id.greater(0)
        it += predicate
    }
    .orderBy(
        Employees.departmentId.desc(),
        Employees.name.asc(),
    )

log.info { q.sql }
```

上述代码中的 `department_id.id>0` 这个语句需要用到联表查询。也输出了预期的查询（虽然不符合您今天讲解的使用规范）：

```sql
SELECT * 
FROM `t_employee` 
LEFT JOIN `t_department` `_ref0` ON `_ref0`.`id` = `t_employee`.`department_id` 
WHERE (((`t_employee`.`name` <> ?) AND ((`t_employee`.`name` = ?) OR (`t_employee`.`id` IN (?, ?, ?, ?)))) OR ((`t_employee`.`manager_id` > ?) AND (`t_employee`.`hire_date` < ?))) OR (`_ref0`.`id` > ?) 
ORDER BY `t_employee`.`department_id` DESC, `t_employee`.`name`
```

不过，如您所见，目前的实现有一个细节不够优雅，其中rsql语句中的字段名称必须与表字段定义中的name值一致，所以导致了 `department_id.id` 这样一个看起来比较奇怪的写法。

这也是个需要向您求助的问题！

**Comment by vincentlauvlwj** [comment]
期待你的 rsql-ktorm 库！！

Ktorm 所谓的规范用法，只是针对普通的开发者，对基于 Ktorm 进行的二次开发，我们不必太在意这些

但是我对 rsql 了解不是很多，所以不太理解你的问题，“rsql语句中的字段名称必须与表字段定义中的name值一致”，想知道是什么造成了这样的限制？

**Comment by vincentlauvlwj** [comment]
我猜测你可能是想通过 rsql 的字段名找到 Ktorm 里面的字段，Ktorm 的 `Employees` 里面确实没有 `department` 这样的字段名，但是我们可以通过别的方式来实现。

`Column` 里面有个 `binding` 属性，它表示这个字段绑定的实体类里面的属性，对于关联表的情况，`binding` 的类型是 `ReferenceBinding`，其中有个 `onProperty` 字段，具体可以看看 [Column.kt](https://github.com/kotlin-orm/ktorm/blob/master/ktorm-core/src/main/kotlin/org/ktorm/schema/Column.kt) 的代码。

通过这个应该可以实现你想要的功能

**Comment by ymind** [comment]
通过 `ReferenceBinding` 已经顺利将 `department_id.id` 这个写法优化为 `department.id`，非常感谢！

不过我又踩了两个坑。

### 一、SqlType.transform()类型判断问题

见代码：https://github.com/kotlin-orm/ktorm/blob/adab090c1a1f224f55b67fa719130760e3762c64/ktorm-core/src/main/kotlin/org/ktorm/schema/SqlType.kt#L86

该方法返回了一个匿名类，所以当某个字段定义了transform之后，我无法判断其类型。我留意到其中包含的 `underlyingType` 字段，如果有办法判断transform后的类型且能获取到 `underlyingType` 字段的值，那么对我会很有用。

相关代码示例：
```kotlin
public fun getExpression(node: ComparisonNode, rsqlOperator: RsqlOperator): ScalarExpression<Boolean>? {
    val column = getColumn(node)
    var converter: FieldValueConverter? = null

    // 根据 SqlType 获取对应的 FieldValueConverter
    //     defaultValueConverters是一堆值类型转换器，目的是将输入值转换为对应 SqlType 的类型
    //     例如 IntValueConverter 的实现为 s.toIntOrNull()
    if (defaultValueConverters.containsKey(column.sqlType)) {
        converter = defaultValueConverters[column.sqlType]
    } else {
        // TODO need ktorm support
        val sqlType = column.sqlType.typeName

        for (defaultValueConverter in defaultValueConverters) {
            if (defaultValueConverter.key.typeName == sqlType) {
                converter = defaultValueConverter.value

                break
            }
        }
    }

    val valueConverter = converter ?: throw TypeNotSupportedException("can not convert values in sqlType: ${column.sqlType.typeName}.")
    val values = valueConverter.convert(node.arguments, sourceTable)

    return operatorAdapter.getExpression(rsqlOperator, column, values, node)
}
```

我的想法是：对于被transform后的字段，一方面可能会转为使用其基础类型（underlyingType）构造查询，另方面可能会交给开发者自行定义查询。因此期望有一个能对其进行判断和取值的途径。

### 二、join别名问题

表结构定义（使得允许从外部自定义departmentId字段的表引用）：
```kotlin
open class Employees(alias: String?, private val departments: Departments) : Table<Employee>("t_employee", alias) {
    companion object : Employees(null, Departments)

    override fun aliased(alias: String) = Employees(alias, departments)

    val id = int("id").primaryKey().bindTo { it.id }
    val name = varchar("name").bindTo { it.name }
    val job = varchar("job").bindTo { it.job }
    val managerId = int("manager_id").bindTo { it.manager?.id }
    val hireDate = date("hire_date").bindTo { it.hireDate }
    val salary = long("salary").bindTo { it.salary }
    val departmentId = int("department_id").references(departments) { it.department }
    val department = departmentId.referenceTable as Departments
}
```

#### 情况1：

```kotlin
val d = Departments.aliased("d")
val e = Employees("e", d)

val q = database.from(e)
    .leftJoin(d, on = d.id.eq(e.departmentId))
    .select(
        e.id,
        e.name,
        e.departmentId,
        d.name,
    )
    .whereWithConditions {
        it += e.job.isNotNull()
        it += d.location.isNotNull() // 注意这里
    }
    .orderBy(
        e.departmentId.desc(),
        e.name.asc(),
        d.location.desc(),
    )
    .limit(0, 10)

/*
    输出SQL：
        SELECT `e`.`id` AS `e_id`, `e`.`name` AS `e_name`, `e`.`department_id` AS `e_department_id`, `d`.`name` AS `d_name`
        FROM `t_employee` `e`
        LEFT JOIN `t_department` `d` ON `d`.`id` = `e`.`department_id`
        WHERE (`e`.`job` IS NOT NULL) AND (`d`.`location` IS NOT NULL)
        ORDER BY `e`.`department_id` DESC, `e`.`name`, `d`.`location` DESC
        LIMIT ?, ?
 */
```

#### 情况2：

```kotlin
val d = Departments.aliased("d")
val e = Employees("e", d)

val q = database.from(e)
    .leftJoin(d, on = d.id.eq(e.departmentId))
    .select(
        e.id,
        e.name,
        e.departmentId,
        d.name,
    )
    .whereWithConditions {
        it += e.job.isNotNull()
        it += e.department.location.isNotNull() // 注意这里
    }
    .orderBy(
        e.departmentId.desc(),
        e.name.asc(),
        d.location.desc(),
    )
    .limit(0, 10)

/*
    输出SQL：
        SELECT `e`.`id` AS `e_id`, `e`.`name` AS `e_name`, `e`.`department_id` AS `e_department_id`, `d`.`name` AS `d_name`
        FROM `t_employee` `e`
        LEFT JOIN `t_department` `d` ON `d`.`id` = `e`.`department_id`
                                              ↓ 这里的别名出现问题
        WHERE (`e`.`job` IS NOT NULL) AND (`_ref0`.`location` IS NOT NULL)
        ORDER BY `e`.`department_id` DESC, `e`.`name`, `d`.`location` DESC
        LIMIT ?, ?
 */
```

跟进代码之后，发现与这里有关：https://github.com/kotlin-orm/ktorm/blob/adab090c1a1f224f55b67fa719130760e3762c64/ktorm-core/src/main/kotlin/org/ktorm/schema/BaseTable.kt#L327

这行代码意味着无论外部是否事先指定别名，都会对其进行覆盖。如果将此处逻辑改为“仅对未指定别名的情况生成别名”，是否会对ktorm整体有影响？

**Comment by vincentlauvlwj** [comment]
`SqlType.transform` 这个问题比较简单，通过 Java 的反射就可以做到，`sqlType.getClass().getDeclaredField("underlyingType")`，判断是否存在 `underlyingType` 这个字段就好了

**Comment by vincentlauvlwj** [comment]
> 使得允许从外部自定义 departmentId 字段的表引用

这个问题，如果没有充分的理由，不会轻易去修改，因为会影响到 Ktorm 的所有跟联表有关的地方。

我不知道你这样做的意义是什么，你明明已经有了一个表对象 `d`，为什么还要使用 `e.department`，不觉得这没什么道理吗...

**Comment by vincentlauvlwj** [comment]
就算同时想用 `d` 和 `e.department`，也可以这样写：

```kotlin
val e = Employees.aliased("e")
val d = e.departmentId.referenceTable as Departments

val q = database.from(e)
    .leftJoin(d, on = d.id.eq(e.departmentId))
    .select(
        e.id,
        e.name,
        e.departmentId,
        d.name,
    )
    .whereWithConditions {
        it += e.job.isNotNull()
        it += e.department.location.isNotNull() // 注意这里
    }
    .orderBy(
        e.departmentId.desc(),
        e.name.asc(),
        d.location.desc(),
    )
    .limit(0, 10)
```

**Comment by ymind** [comment]
> `SqlType.transform` 这个问题比较简单，通过 Java 的反射就可以做到，`sqlType.getClass().getDeclaredField("underlyingType")`，判断是否存在 `underlyingType` 这个字段就好了

是的，的确想过反射解决。但如果这里的机制可以重构为一个normal class，那么我就可以不用反射啦~

**Comment by ymind** [comment]
> > 使得允许从外部自定义 departmentId 字段的表引用
> 
> 这个问题，如果没有充分的理由，不会轻易去修改，因为会影响到 Ktorm 的所有跟联表有关的地方。
> 
> 我不知道你这样做的意义是什么，你明明已经有了一个表对象 `d`，为什么还要使用 `e.department`，不觉得这没什么道理吗...

当然，我提供的是一个容易理解的DSL代码示例。实际上我的需求是解析rsql语句中类似于`department.location`、`department.name`等这样的查询，它势必会经历 `table.aliased("_ref${_refCounter.getAndIncrement()}") ` 这段代码。如果我不使用自定义别名则一切正常，但为了严谨起见就去评估了一下如果带上自定义别名会怎样，所以就尝试了一下。之后便遇到了这个问题。

如果此处重构会给框架带来重大隐患，也没有关系。我认为自定义别名的情况还是很少发生的。

**Comment by vincentlauvlwj** [comment]
> 我认为自定义别名的情况还是很少发生的。

不是很少发生，根本就是错误用法，Ktorm 的文档里面从来没说过可以这样用，`references` 函数的代码注释里面也说明了会调用 `aliased` 函数把表对象复制一份 https://github.com/kotlin-orm/ktorm/blob/master/ktorm-core/src/main/kotlin/org/ktorm/schema/Table.kt#L81-L82

**Comment by ymind** [comment]
> > 我认为自定义别名的情况还是很少发生的。
> 
> 不是很少发生，根本就是错误用法，Ktorm 的文档里面从来没说过可以这样用，`references` 函数的代码注释里面也说明了会调用 `aliased` 函数把表对象复制一份 https://github.com/kotlin-orm/ktorm/blob/master/ktorm-core/src/main/kotlin/org/ktorm/schema/Table.kt#L81-L82

收到，我也将在文档中指明这一点！

**Comment by ymind** [comment]
今天又遇到一个联表查询相关的问题，复现过程如下：

1、找到如下代码：
https://github.com/kotlin-orm/ktorm/blob/adab090c1a1f224f55b67fa719130760e3762c64/ktorm-support-sqlserver/src/test/kotlin/org/ktorm/support/sqlserver/SqlServerTest.kt#L78-L85

2、将其中的排序语句改为：
```kotlin
.orderBy(Employees.id.desc(), Employees.department.location.desc())
```

3、运行单元测试，将会抛出如下错误：
```
[INFO] Connected to jdbc:sqlserver://localhost:49186;useBulkCopyForBatchInsert=false;cancelQueryTimeout=-1;sslProtocol=TLS;jaasConfigurationName=SQLJDBCDriver;statementPoolingCacheSize=0;serverPreparedStatementDiscardThreshold=10;enablePrepareOnFirstPreparedStatementCall=false;fips=false;socketTimeout=0;authentication=NotSpecified;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustStoreType=JKS;trustServerCertificate=false;TransparentNetworkIPResolution=true;serverNameAsACE=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;queryTimeout=-1;packetSize=8000;multiSubnetFailover=false;loginTimeout=15;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;columnEncryptionSetting=Disabled;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite;, productName: Microsoft SQL Server, productVersion: 14.00.3045, logger: org.ktorm.logging.ConsoleLogger@735a5972, dialect: org.ktorm.support.sqlserver.SqlServerDialect@3ad39de4
[DEBUG] SQL: SELECT COUNT(*) FROM t_employee LEFT JOIN t_department ON t_employee.department_id = t_department.id 
[DEBUG] Parameters: []
[DEBUG] Results: 1
[DEBUG] Total Records: 4
[DEBUG] SQL: SELECT * FROM (SELECT TOP 1 *, ROW_NUMBER() OVER(ORDER BY _t1.t_employee_id DESC, _t1.location DESC) _ROWNUM FROM (SELECT t_employee.id AS t_employee_id, t_employee.name AS t_employee_name FROM t_employee LEFT JOIN t_department ON t_employee.department_id = t_department.id) _t1 ) _t2 WHERE _ROWNUM >= 1 
[DEBUG] Parameters: []

Invalid column name 'location'.
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'location'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621)
	...
	at java.base/java.lang.Thread.run(Thread.java:834)


org.ktorm.support.sqlserver.SqlServerTest > testPagingSql FAILED
```

**Comment by vincentlauvlwj** [comment]
都说了 `Departments` 和 `Employees.department` 是两个完全不同的表对象，前面 `leftJoin` 的时候用的是 `Departments`，为什么 `orderBy` 的时候又变成了 `Employees.department` 呢？

**Comment by ymind** [comment]
刚刚试了一下，如果将排序语句改为：
```kotlin
.orderBy(Employees.id.desc(), Departments.location.desc())
```
仍然会报错：

```
[INFO] Connected to jdbc:sqlserver://localhost:49183;useBulkCopyForBatchInsert=false;cancelQueryTimeout=-1;sslProtocol=TLS;jaasConfigurationName=SQLJDBCDriver;statementPoolingCacheSize=0;serverPreparedStatementDiscardThreshold=10;enablePrepareOnFirstPreparedStatementCall=false;fips=false;socketTimeout=0;authentication=NotSpecified;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustStoreType=JKS;trustServerCertificate=false;TransparentNetworkIPResolution=true;serverNameAsACE=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;queryTimeout=-1;packetSize=8000;multiSubnetFailover=false;loginTimeout=15;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;columnEncryptionSetting=Disabled;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite;, productName: Microsoft SQL Server, productVersion: 14.00.3045, logger: org.ktorm.logging.ConsoleLogger@ae8743a, dialect: org.ktorm.support.sqlserver.SqlServerDialect@170d16b4
[DEBUG] SQL: SELECT COUNT(*) FROM t_employee LEFT JOIN t_department ON t_employee.department_id = t_department.id 
[DEBUG] Parameters: []
[DEBUG] Results: 1
[DEBUG] Total Records: 4
[DEBUG] SQL: SELECT * FROM (SELECT TOP 1 *, ROW_NUMBER() OVER(ORDER BY _t1.t_employee_id DESC, _t1.location DESC) _ROWNUM FROM (SELECT t_employee.id AS t_employee_id, t_employee.name AS t_employee_name FROM t_employee LEFT JOIN t_department ON t_employee.department_id = t_department.id) _t1 ) _t2 WHERE _ROWNUM >= 1 
[DEBUG] Parameters: []

Invalid column name 'location'.
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'location'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621)
```

**Comment by vincentlauvlwj** [comment]
这是另一个问题，sql server 要求排序的字段必须出现在 select 里面，需要这样写：

```kotlin
select(Employees.id, Employees.name, Departments.location)
```

**Comment by ymind** [comment]
收到，按照您的指点已调试通过！~
