### ISSUE TITLE
无法使用kotlin unsigned类型进行扩展

### ISSUE THREAD

**Issue by yh0xa55a8** [kotlin-orm/ktorm#253]
Ktorm version: 3.2.0

扩展的代码
```kotlin
object ULongSqlType: SqlType<ULong>(Types.BIGINT, "bigint unsigned") {
    override fun doGetResult(rs: ResultSet, index: Int): ULong? =
        (rs.getObject(index) as? BigInteger)?.toLong()?.toULong()

    override fun doSetParameter(ps: PreparedStatement, index: Int, parameter: ULong) =
        ps.setLong(index, parameter.toLong())
}

fun BaseTable<*>.ulong(name: String) = this.registerColumn(name, ULongSqlType)
```

对应的Table object
```kotlin
object Users: Table<User>("user") {
    val id = ulong("id")
        .primaryKey()
        .bindTo { it.id }
}
```
配合spring boot使用
在User object初始化时报错：
```
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.lang.reflect.InvocationHandler.invoke(Object, java.lang.reflect.Method, Object[])" is null
        at com.sun.proxy.$Proxy133.getId-s-VKNKU(Unknown Source) ~[na:na]
	at cn.yh0x13f.teatalk.data.sql.table.Users.<clinit>(Users.kt:10) ~[main/:na]
```
断点可见问题出现在`bindTo { it.id }`
推测问题抛出在获取实体列绑定的properties中

**Comment by yh0xa55a8** [comment]
更新  问题定位到org.ktorm.schema.ColumnBindingHandler[58]的return  因为unsigned type不是基本类型  所以此处返回了null，而外层一个定位不到的地方试图以此为结果转换到java.lang.Long （为什么会有这样的行为啊）然后就抛出了

**Comment by vincentlauvlwj** [comment]
`ColumnBindingHandler` 是一个用于动态代理的类，它的目的是记录我们在 `bind { }` 方法的 lambda 表达式里面返回的具体是哪个属性，所以它的 `invoke` 方法的返回值实际上是没有意义的，因此才会有基本类型返回默认值，其他类型直接返回 null 的逻辑

`ULong` 是一个 inline class，这个类在 Java 里面不是基本类型，所以返回 null 了，但是 inline class 的行为有点特殊，它在编译时会视为其包装的基本类型，所以才会出现这个问题

解决方法：暂时先改成 `Long`，不要用 `ULong`，Ktorm 在下个版本会做一下兼容

**Comment by vincentlauvlwj** [comment]
3.4.0 版本已兼容无符号整数

**Comment by vincentlauvlwj** [comment]
3.5.0 版本已完全兼容所有内联类型
