### ISSUE TITLE
Support build native image

### ISSUE THREAD

**Issue by lucy9x** [kotlin-orm/ktorm#310]
I am using ktorm in quarkus. Build the native image is success but error when executing binary file. Seems to be related to the reflection. This is error stacktrace when execute the binary file.

```
ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Unresolved class: interface io.lucy.database.Department
        at kotlin.reflect.jvm.internal.KClassImpl.reportUnresolvedClass(KClassImpl.kt:325)
        at kotlin.reflect.jvm.internal.KClassImpl.access$reportUnresolvedClass(KClassImpl.kt:44)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:56)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:47)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$supertypes$2.invoke(KClassImpl.kt:125)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$supertypes$2.invoke(KClassImpl.kt:47)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getSupertypes(KClassImpl.kt)
        at kotlin.reflect.jvm.internal.KClassImpl.getSupertypes(KClassImpl.kt:254)
        at kotlin.reflect.full.KClasses.getSuperclasses(KClasses.kt:185)
        at kotlin.reflect.full.KClasses$isSubclassOf$1.get(KClasses.kt:234)
        at kotlin.jvm.internal.PropertyReference1.invoke(PropertyReference1.java:35)
        at kotlin.reflect.full.KClasses$sam$org_jetbrains_kotlin_utils_DFS_Neighbors$0.getNeighbors(KClasses.kt)
        at kotlin.reflect.jvm.internal.impl.utils.DFS.doDfs(DFS.java:98)
        at kotlin.reflect.jvm.internal.impl.utils.DFS.dfs(DFS.java:27)
        at kotlin.reflect.jvm.internal.impl.utils.DFS.dfs(DFS.java:37)
        at kotlin.reflect.jvm.internal.impl.utils.DFS.ifAny(DFS.java:47)
        at kotlin.reflect.full.KClasses.isSubclassOf(KClasses.kt:234)
        at org.ktorm.entity.Entity$Companion.create$ktorm_core(Entity.kt:246)
        at org.ktorm.entity.Entity$Companion.create$ktorm_core$default(Entity.kt:244)
        at org.ktorm.schema.Table.doCreateEntity(Table.kt:128)
        at org.ktorm.schema.Table.doCreateEntity(Table.kt:50)
        at org.ktorm.schema.BaseTable.createEntity(BaseTable.kt:353)
        at org.ktorm.schema.BaseTable.createEntity$default(BaseTable.kt:352)
        at io.lucy.Application.onStart(Application.kt:20)
        at io.lucy.Application_Subclass.onStart$$superaccessor1(Application_Subclass.zig:213)
        at io.lucy.Application_Subclass$$function$$1.apply(Application_Subclass$$function$$1.zig:33)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:127)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.lucy.Application_Subclass.onStart(Application_Subclass.zig:170)
        at io.lucy.Application_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(Application_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:147)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:283)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:268)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:675)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```

**Comment by wangtao94** [comment]
请问你解决这个问题了吗？
