### ISSUE TITLE
StackOverflowError when using too many whereWithOrConditions

### ISSUE THREAD

**Issue by ecopoesis** [kotlin-orm/ktorm#327]
When there are too many `whereWithOrConditions` conditions the JVM will throw a `StackOverflowError` because `SqlFormatter` is recursive. 

Code that causes the error:
```kotlin
    interface TestTable : Entity<TestTable> {
        companion object : Entity.Factory<TestTable>()

        val id1: Long
        val id2: Long
    }

    object TestTables : Table<TestTable>("test") {
        val id1: Column<Long> = long("id1").primaryKey().bindTo { it.id1 }
        val id2: Column<Long> = long("id2").bindTo { it.id2 }
    }

    @Test
    fun stackOverflow() {
        val query = database
            .from(TestTables)
            .select()
            .whereWithOrConditions { where ->
                repeat(1200) {
                    where += (TestTables.id1 eq Random.nextLong()) and (TestTables.id2 eq Random.nextLong())
                }
            }

        println(query.sql)
    }
```

Partial error:
```
java.lang.StackOverflowError
	at kotlin.jvm.internal.Intrinsics.checkNotNullParameter(Intrinsics.java)
	at org.ktorm.support.mysql.MySqlFormatter.visitScalar(MySqlDialect.kt)
	at org.ktorm.expression.SqlExpressionVisitor.visit(SqlExpressionVisitor.kt:45)
	at org.ktorm.expression.SqlFormatter.visit(SqlFormatter.kt:189)
	at org.ktorm.support.mysql.MySqlFormatter.visit(MySqlDialect.kt:46)
	at org.ktorm.expression.SqlFormatter.visitBinary(SqlFormatter.kt:244)
	at org.ktorm.expression.SqlExpressionVisitor.visitScalar(SqlExpressionVisitor.kt:63)
	at org.ktorm.support.mysql.MySqlFormatter.visitScalar(MySqlDialect.kt:56)
	at org.ktorm.expression.SqlExpressionVisitor.visit(SqlExpressionVisitor.kt:45)
	at org.ktorm.expression.SqlFormatter.visit(SqlFormatter.kt:189)
	at org.ktorm.support.mysql.MySqlFormatter.visit(MySqlDialect.kt:46)
	at org.ktorm.expression.SqlFormatter.visitBinary(SqlFormatter.kt:244)
	at org.ktorm.expression.SqlExpressionVisitor.visitScalar(SqlExpressionVisitor.kt:63)
	at org.ktorm.support.mysql.MySqlFormatter.visitScalar(MySqlDialect.kt:56)
	at org.ktorm.expression.SqlExpressionVisitor.visit(SqlExpressionVisitor.kt:45)
	at org.ktorm.expression.SqlFormatter.visit(SqlFormatter.kt:189)
	at org.ktorm.support.mysql.MySqlFormatter.visit(MySqlDialect.kt:46)
	at org.ktorm.expression.SqlFormatter.visitBinary(SqlFormatter.kt:244)
	at org.ktorm.expression.SqlExpressionVisitor.visitScalar(SqlExpressionVisitor.kt:63)
        ...
```

**Comment by vincentlauvlwj** [comment]
In a real world program, I can't image a query can have 1200 conditions. 😂

**Comment by ecopoesis** [comment]
I assure you that I ran into this in my very real world program yesterday. 

Many small DB calls have a lot of overhead: merging similar calls into bulk calls is a common pattern. We compute how many items we can stuff into a bulk call based on MySQL’s packet size to limit our number of DB calls. In this case our computed limit is ~13000. 

Another reason to reduce or eliminate recursion here is that it’s slow. To work around this I’ve hardcoded our bucket size to 512, but even at that small number generating the SQL is the lowest part.

**Comment by ecopoesis** [comment]
I've opened a PR that fixes this issue: https://github.com/kotlin-orm/ktorm/pull/328
