### ISSUE TITLE
java.lang.NoSuchMethodError: kotlin.collections.MapsKt.createMapBuilder()Ljava/util/Map;

### ISSUE THREAD

**Issue by zhangwei911** [kotlin-orm/ktorm#331]
```
java.lang.NoSuchMethodError: kotlin.collections.MapsKt.createMapBuilder()Ljava/util/Map;
	at kotlin.reflect.jvm.internal.impl.descriptors.Visibilities.<clinit>(Visibilities.kt:56)
	at kotlin.reflect.jvm.internal.impl.descriptors.Visibility.compareTo(Visibility.kt:23)
	at kotlin.reflect.jvm.internal.impl.descriptors.DescriptorVisibility.compareTo(DescriptorVisibility.kt:61)
	at kotlin.reflect.jvm.internal.impl.descriptors.DescriptorVisibilities.compare(DescriptorVisibilities.java:325)
	at kotlin.reflect.jvm.internal.impl.resolve.OverridingUtil.findMaxVisibility(OverridingUtil.java:976)
	at kotlin.reflect.jvm.internal.impl.resolve.OverridingUtil.computeVisibilityToInherit(OverridingUtil.java:935)
	at kotlin.reflect.jvm.internal.impl.resolve.OverridingUtil.resolveUnknownVisibilityForMember(OverridingUtil.java:900)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$generateFakeOverrides$1.addFakeOverride(DeserializedClassDescriptor.kt:315)
	at kotlin.reflect.jvm.internal.impl.resolve.OverridingUtil.createAndBindFakeOverride(OverridingUtil.java:732)
	at kotlin.reflect.jvm.internal.impl.resolve.OverridingUtil.createAndBindFakeOverrides(OverridingUtil.java:565)
	at kotlin.reflect.jvm.internal.impl.resolve.OverridingUtil.generateOverridesInFunctionGroup(OverridingUtil.java:500)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.generateFakeOverrides(DeserializedClassDescriptor.kt:307)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.computeNonDeclaredProperties(DeserializedClassDescriptor.kt:298)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.computeProperties(DeserializedMemberScope.kt:315)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.access$computeProperties(DeserializedMemberScope.kt:228)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation$properties$1.invoke(DeserializedMemberScope.kt:253)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation$properties$1.invoke(DeserializedMemberScope.kt:253)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:651)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.getContributedVariables(DeserializedMemberScope.kt:338)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$OptimizedImplementation.addFunctionsAndPropertiesTo(DeserializedMemberScope.kt:352)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.computeDescriptors(DeserializedMemberScope.kt:115)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.kt:257)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.kt:256)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getContributedDescriptors(DeserializedClassDescriptor.kt:267)
	at kotlin.reflect.jvm.internal.impl.resolve.scopes.ResolutionScope$DefaultImpls.getContributedDescriptors$default(ResolutionScope.kt:50)
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.getMembers(KDeclarationContainerImpl.kt:56)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:162)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:47)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDeclaredNonStaticMembers(KClassImpl.kt)
	at kotlin.reflect.full.KClasses.getDeclaredMemberProperties(KClasses.kt:163)
	at org.ktorm.schema.ColumnBindingHandlerKt.getKotlinProperty(ColumnBindingHandler.kt:76)
	at org.ktorm.schema.ColumnBindingHandler.invoke(ColumnBindingHandler.kt:42)
	at com.sun.proxy.$Proxy65.getId(Unknown Source)
```
```
interface Task : Entity<Task > {
    companion object : Entity.Factory<Task >()

    /**
     * id
     */
    var id: String
}
object EaipTasks : Table<Task>("l_task") {
  val id = varchar("id").bindTo { it.id }
}
```

这个也是 #330 的根本原因

**Comment by vincentlauvlwj** [comment]
恭喜你找到了错误原因，但是这并不是 Ktorm 的问题，而是你项目里面有依赖冲突

**Comment by vincentlauvlwj** [comment]
检查一下你项目里面 kotlin-stdlib 和 kotlin-reflect 的版本号是否对应

**Comment by vincentlauvlwj** [comment]
`MapsKt.createMapBuilder` 是 Kotlin 1.3 新增的方法，所以我才你的 kotlin-reflect 版本号可能是 1.2 左右..

**Comment by zhangwei911** [comment]
> `MapsKt.createMapBuilder` 是 Kotlin 1.3 新增的方法，所以我猜你的 kotlin-reflect 版本号可能是 1.2 左右..

我用的1.5.30

**Comment by zhangwei911** [comment]
而且这个错是declaringClass.kotlin.declaredMemberProperties导致的

**Comment by zhangwei911** [comment]
另外MapsKt.createMapBuilder是一个ExperimentalStdlibApi

**Comment by vincentlauvlwj** [comment]
> `MapsKt.createMapBuilder` 是 Kotlin 1.3 新增的方法，所以我猜你的 kotlin-reflect 版本号可能是 1.2 左右..

搞错了，版本太低的应该是 kotlin-stdlib 这个库，你可以百度一下 maven 或者 gradle 是如何解决依赖版本冲突的

**Comment by zhangwei911** [comment]
我的项目没有用gradle,就是一个普通的springmvc项目,spring是4.3.22
我今天迁移到gradle,加上-Xopt-in=kotlin.RequiresOptIn就不报这个错了
但是问题依旧没有解决,只是规避了而已
