### ISSUE TITLE
connecting to database with url in jar

### ISSUE THREAD

**Issue by luckaB** [kotlin-orm/ktorm#355]
I am trying to connect to a database with the following code:
```
val dbFileName= ClassLoader.getSystemClassLoader().getResource("myDb.sqlite") as URL
val database = Database.connect(
        url = "jdbc:sqlite:${dbFileName.path}",
        driver = "org.sqlite.JDBC",
    )
```
This runs without any error, when called directly (e.g. from my IDE)

However, when I build and pack the code to a jar and run that, I get the following error:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file)
	at org.sqlite.core.DB.newSQLException(DB.java:1010)
	at org.sqlite.core.DB.newSQLException(DB.java:1022)
	at org.sqlite.core.DB.throwex(DB.java:987)
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:78)
	at org.sqlite.core.DB.open(DB.java:202)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:243)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
	at org.sqlite.JDBC.createConnection(JDBC.java:115)
	at org.sqlite.JDBC.connect(JDBC.java:90)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.ktorm.database.Database$Companion$connect$2.invoke(Database.kt:603)
	at org.ktorm.database.Database$Companion$connect$2.invoke(Database.kt:521)
	at org.ktorm.database.JdbcTransactionManager.newConnection(JdbcTransactionManager.kt:51)
	at org.ktorm.database.Database.<init>(Database.kt:793)
	at org.ktorm.database.Database.<init>(Database.kt:138)
	at org.ktorm.database.Database$Companion.connect(Database.kt:602)
	at org.ktorm.database.Database$Companion.connect$default(Database.kt:596)
```

It seems that the `connect` method cannoct handle resources zipped in a jar file - is there a way to make it work?

**Comment by vincentlauvlwj** [comment]
You should raise this issue to SQLite.
