### ISSUE TITLE
请问如何定义常量 as 写法呢？

### ISSUE THREAD

**Issue by praynise** [kotlin-orm/ktorm#360]
例如select(
    NameLists.Name,
    LocalDateTime.now()
)
这种写法需要如何实现呢？非常感谢

**Comment by praynise** [comment]
我找到了方法用ArgumentExpression(LocalDate.now(), LocalDateSqlType).aliased("rs_date")替换上面的LocalDateTime.now()，但是后面要如何把这个值取出来呢？即存字段使用row[NameLists.Name]就可以取到，但是这个自己定义的虚拟列如何以相同的方式获取呢？烦请指点，非常感谢

**Comment by vincentlauvlwj** [comment]
先用一个变量保存你的别名列

```kotlin
val col = ArgumentExpression(LocalDate.now(), LocalDateSqlType).aliased("rs_date")
```

取结果的时候，把这个别名列传进去就可以了

```kotlin
val result = row[col]
```

**Comment by praynise** [comment]
您好！感谢回复，但是我遇到了另外一个问题，当我使用LocalDate和LocalDateTime类型的常量列时会报错，当使用LocalDate时报错为
```
Exception in thread "main" java.lang.IllegalArgumentException
	at java.sql.Date.valueOf(Date.java:143)
	at org.ktorm.database.CachedRowSet.getDate(CachedRowSet.kt:420)
	at org.ktorm.schema.LocalDateSqlType.doGetResult(SqlTypes.kt:376)
	at org.ktorm.schema.LocalDateSqlType.doGetResult(SqlTypes.kt:370)
	at org.ktorm.schema.SqlType.getResult(SqlType.kt:59)
	at org.ktorm.dsl.QueryRowSet.get(QueryRowSet.kt:95)
	at MainKt.main(main.kt:45)
	at MainKt.main(main.kt)
```
当使用LocalDateTime时报错为
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "933+08000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.sql.Timestamp.valueOf(Timestamp.java:255)
	at org.ktorm.database.CachedRowSet.getTimestamp(CachedRowSet.kt:470)
	at org.ktorm.schema.LocalDateTimeSqlType.doGetResult(SqlTypes.kt:356)
	at org.ktorm.schema.LocalDateTimeSqlType.doGetResult(SqlTypes.kt:350)
	at org.ktorm.schema.SqlType.getResult(SqlType.kt:59)
	at org.ktorm.dsl.QueryRowSet.get(QueryRowSet.kt:95)
	at MainKt.main(main.kt:45)
	at MainKt.main(main.kt)
```
还望帮助，非常感谢~
