### ISSUE TITLE
insertOrUpdateReturning does not work with HikariCP

### ISSUE THREAD

**Issue by asad-awadia** [kotlin-orm/ktorm#368]
When running an insertOrUpdateReturning on ktorm 3.4.1 using a HikariCP data source I keep getting an error

```
fun main() {
  val database = Database.connect(getHikariDs(), logger = ConsoleLogger(LogLevel.DEBUG))
  val insertOrUpdateReturning = database.insertOrUpdateReturning(Users, Users.id) {
    set(it.apiKey UlidCreator.getUlid().toLowerCase())
    set(it.id, "12")
    onConflict(it.id, it.apiKey) {
      doNothing()
    }
  }
  println(insertOrUpdateReturning)
}

fun getHikariDs(): HikariDataSource {
  val props = Properties()
  props.setProperty("dataSourceClassName", "com.impossibl.postgres.jdbc.PGDataSource")
  props.setProperty("dataSource.user", "postgres")
  props.setProperty("dataSource.password", "password")
  props.setProperty("dataSource.databaseName", "postgres")
  val config = HikariConfig(props)
  config.jdbcUrl = "postgresql://localhost:5432/postgres?sslmode=disable"
  return HikariDataSource(config)
}
```

```
[INFO] Connected to jdbc:pgsql://localhost/postgres, productName: PostgreSQL, productVersion: 14.1, logger: org.ktorm.logging.ConsoleLogger@831ea0ad, dialect: org.ktorm.support.postgresql.PostgreSqlDialect@17d37c5c
[DEBUG] SQL: insert into users (id, api_key) values (?, ?) on conflict (id, api_key) do nothing returning id
[DEBUG] Parameters: [12(text), 01ftrfbt8mjjxfw1xgf31012ae(text)]
Exception in thread "main" com.impossibl.postgres.jdbc.PGSQLSimpleException: syntax error at or near "RETURNING"
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:197)
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:174)
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:161)
	at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:514)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.lambda$describeIfNeeded$1(PGPreparedStatement.java:247)
	at com.impossibl.postgres.jdbc.PGPreparedStatement$$Lambda$247/0x00000000f9503638.load(Unknown Source)
	at com.impossibl.postgres.jdbc.PGDirectConnection.getCachedStatementDescription(PGDirectConnection.java:1564)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.describeIfNeeded(PGPreparedStatement.java:245)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.resolveType(PGPreparedStatement.java:149)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.set(PGPreparedStatement.java:170)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.set(PGPreparedStatement.java:163)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.setString(PGPreparedStatement.java:669)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setString(HikariProxyPreparedStatement.java)
	at org.ktorm.schema.TextSqlType.doSetParameter(SqlTypes.kt:206)
	at org.ktorm.schema.TextSqlType.doSetParameter(SqlTypes.kt:204)
	at org.ktorm.schema.SqlType.setParameter(SqlType.kt:51)
	at org.ktorm.database.JdbcExtensionsKt.setArguments(JdbcExtensions.kt:58)
	at org.ktorm.database.SqlDialect$DefaultImpls.executeUpdateAndRetrieveKeys(SqlDialect.kt:76)
	at org.ktorm.support.postgresql.PostgreSqlDialect.executeUpdateAndRetrieveKeys(PostgreSqlDialect.kt:27)
	at org.ktorm.database.Database.executeUpdateAndRetrieveKeys(Database.kt:462)
	at org.ktorm.support.postgresql.InsertOrUpdateKt.insertOrUpdateReturningRow(InsertOrUpdate.kt:238)
	at org.ktorm.support.postgresql.InsertOrUpdateKt.insertOrUpdateReturning(InsertOrUpdate.kt:128)
```

but if I run the above with the connection string directly it does work and not use hikari it does work - even using the sql directly in terminal seems to be workimg

**Comment by asad-awadia** [comment]
@vincentlauvlwj

**Comment by lookup-cat** [comment]
This problem seems to be the driver implementation problem of "pgjdbc-ng". After I tried to replace the jdbc driver with "org.postgresql.Driver", it can be executed successfully

![image](https://user-images.githubusercontent.com/45026715/156594764-0b4ed4c8-36e6-472f-9d22-e8aa85337b59.png)

You can add dependency "org.postgresql:postgresql:42.2.5" in gradle, and then try to replace jdbc driver with "org.postgresql.Driver"

**Comment by asad-awadia** [comment]
@lookup-cat will that still give proper connection pooling?

**Comment by lookup-cat** [comment]
Of course, using either Driver or Datasource will provide HikariCP with the correct connection pool. In most cases, there is no difference between the two methods. You can also make HIkariCP receive a DataSource by

```kotlin
props.setProperty("dataSourceClassName", "org.postgresql.ds.PGSimpleDataSource")
```

More information about this can be found in the HikariCP documentation
[https://github.com/brettwooldridge/HikariCP](https://github.com/brettwooldridge/HikariCP)

**Comment by asad-awadia** [comment]
@lookup-cat right, but like some sources don't provide pooling even with hikari - like the simple pg one 

But good to know this will still give proper pooling support

Thank you
