### ISSUE TITLE
connectWithSpringSupport出现空指针异常

### ISSUE THREAD

**Issue by Gargantua7** [kotlin-orm/ktorm#376]
线上环境出现了NPE，测试环境却无法复现
查看日志：
```
java.lang.NullPointerException: translator.translate("Ktorm", null, ex) must not be null
	at org.ktorm.database.Database$Companion$connectWithSpringSupport$1.invoke(Database.kt:639) ~[ktorm-core-3.4.1.jar!/:na]
	at org.ktorm.database.Database$Companion$connectWithSpringSupport$1.invoke(Database.kt:520) ~[ktorm-core-3.4.1.jar!/:na]
```
对应库中源码：
```
exceptionTranslator = { ex -> translator.translate("Ktorm", null, ex) },
```
猜测是`translate`方法为`Nullable`而`exceptionTranslator`仅接收`Throwable`类型参数

`spring-boot-starter-jdbc`版本为`2.6.2`，对应`spring-jdbc`版本为`5.3.14`
`ktorm`版本为`3.4.1`

**Comment by Gargantua7** [comment]
经过排查，我发现引起此问题的原因是我使用了自定SQL语句同时执行出错，更改为正确的SQL语句后不再出现此问题
但是我认为Ktorm应该对此NPE进行一些封装提示或者处理

**Comment by abop** [comment]
> 经过排查，我发现引起此问题的原因是我使用了自定SQL语句同时执行出错，更改为正确的SQL语句后不再出现此问题 但是我认为Ktorm应该对此NPE进行一些封装提示或者处理

这里应该分为两个问题：
1. `sql` 错误，与框架无关 
2. `exceptionTranslator` 声明为 `return non-null`，但 `connectWithSpringSupport `用到的 `org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator` 在 `translator.translate("Ktorm", null, ex) `时会返回 `null`

第2点我认为是框架没有正确处理，`exceptionTranslator`应该声明为 
```
public val exceptionTranslator: ((SQLException) -> Throwable?)? = null,
```

**Comment by vincentlauvlwj** [comment]
@abop 有道理，之前没有注意到，后续考虑优化

**Comment by abop** [comment]
> @abop 有道理，之前没有注意到，后续考虑优化

@vincentlauvlwj #524 我看已经有 PR 了
