### ISSUE TITLE
Springboot Get Request Param Mapping Error

### ISSUE THREAD

**Issue by kuolemax** [kotlin-orm/ktorm#404]
**Question description**

Exception occurs when I try to use Entity Interface to accept parameters.

**Example**

```kotlin
// DepartmentController.kt
@RestController
@RequestMapping("department")
class DepartmentController(val database: Database) {
    @GetMapping
    fun listDepartment(@ModelAttribute item: Department?) : List<Department>?{
        return database.departments
            .toList()
    }
    
    or
    
    @GetMapping
    fun listDepartment(item: Department?) : List<Department>?{
        return database.departments
            .toList()
    }
}
```

```kotlin
// Department.kt
interface Department : Entity<Department> {
    companion object : Entity.Factory<Department>()

    /** 部门识别码 */
    var key: String?

    /** 部门名称 */
    var name: String?

    /** 部门地址 */
    var location: String?

    /** 负责人 */
    var picId: Long?

    /** 部门人数 */
    var count: Int?

    var id: Long
    var exist: Boolean
    var createdAt: Timestamp
    var updatedAt: Timestamp
}
```

**Request URL**

```http
GET http://localhost:3000/department
```

**Error**

```text
java.lang.IllegalStateException: No primary or single unique constructor found for interface cn.kuolemax.ktorm_automation.model.Department
	at org.springframework.beans.BeanUtils.getResolvableConstructor(BeanUtils.java:267)
	at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.createAttribute(ModelAttributeMethodProcessor.java:219)
	at org.springframework.web.servlet.mvc.method.annotation.ServletModelAttributeMethodProcessor.createAttribute(ServletModelAttributeMethodProcessor.java:85)
	at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.resolveArgument(ModelAttributeMethodProcessor.java:147)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by vincentlauvlwj** [comment]
please follow the example https://github.com/kotlin-orm/ktorm-example-spring-boot/blob/master/src/main/kotlin/org/ktorm/example/configuration/KtormConfiguration.kt

**Comment by kuolemax** [comment]
These configurations have been, and POST request is ok，only GET error
```kotlin
@Configuration
class KtormConfiguration(var dataSource: DataSource) {

    @Bean
    fun ktormJacksonModule(): Module = KtormModule()

    @Bean
    fun database(): Database {
        return Database.connectWithSpringSupport(dataSource)
    }
}
```

**Comment by vincentlauvlwj** [comment]
`@ModelAttribute` is not supported, use `@RequestParam` instead.

**Comment by kuolemax** [comment]
I can't do this, please check out the article

https://tedblob.com/spring-boot-bind-request-parameters-to-object/

> Note that we haven’t specified the @RequestParam annotation as it cannot bind the POJO object to a web request parameter. You can use Spring bean validation to validate the fields of POJO object. See[ this article](https://tedblob.com/spring-boot-validate-request-body/) for more details.

**Comment by vincentlauvlwj** [comment]
Then you can define a DTO class for your request object. Anyway, DONOT use ktorm's entities along with `@ModelAttribute`  because they are not standard POJO.

```kotlin
data class DepartmentRequestDTO(val id: Long, val name: String)

@GetMapping
fun listDepartment(@ModelAttribute request: DepartmentRequestDTO) : List<Department> { }
```

**Comment by kuolemax** [comment]
Well, while doing this makes the code redundant, there is no better way. Thanks for helping.
