### ISSUE TITLE
在Quarkus中使用interface作为实体类，无法序列化：No serializer found for class kotlin.reflect.jvm.internal.ReflectProperties$LazyVal

### ISSUE THREAD

**Issue by seepine** [kotlin-orm/ktorm#429]
```kt
interface User : Entity<User> {
    companion object : Entity.Factory<User>()

    var id: Long
    var avatarUrl: String
    var nickName: String
}
```
```kt
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    fun get(): User {
        return User{id=1}
    }
```

```shell
2022-08-31 20:18:48,842 ERROR [io.qua.res.rea.jac.run.map.NativeInvalidDefinitionExceptionMapper] (executor-thread-0) com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class kotlin.reflect.jvm.internal.ReflectProperties$LazyVal and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.sun.proxy.$Proxy64["entityClass"]->kotlin.reflect.jvm.internal.KClassImpl["data"])
2022-08-31 20:18:48,842 DEBUG [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Failed to close stream: java.io.IOException: java.io.IOException: Failed to write
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.close(ResteasyReactiveOutputStream.java:303)
	at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.close(ResteasyReactiveRequestContext.java:362)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:185)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Failed to write
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:112)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.writeBlocking(ResteasyReactiveOutputStream.java:227)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.close(ResteasyReactiveOutputStream.java:301)
	... 9 more
Caused by: java.lang.IllegalStateException: Response has already been written
	at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:400)
	at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:388)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:103)
	... 11 more
```

**Comment by vincentlauvlwj** [comment]
https://www.ktorm.org/zh-cn/entities-and-column-binding.html#%E5%BA%8F%E5%88%97%E5%8C%96

**Comment by vincentlauvlwj** [comment]
依赖冲突的问题，与 ktorm 无关，自己百度一下如何解决
