### ISSUE TITLE
leftJoin关联两个相同类型的字段，createEntity无法填充

### ISSUE THREAD

**Issue by yhsj0919** [kotlin-orm/ktorm#519]
```kotlin
val creator = Users.aliased("creator")
val editor = Users.aliased("editor")
val data = mysql()
            .from(Orders)
            .leftJoin(creator, on = Orders.creator eq creator.id)
            .leftJoin(editor, on = Orders.editor eq editor.id)
            .select()
            .map { row ->
                Orders.createEntity(row)
            }
```

```
报错如下：
java.lang.IllegalArgumentException: Confused column name, there are more than one column named 'id' in query: 
```

去掉一个leftJoin就正常

**Comment by vincentlauvlwj** [comment]
参考这里 https://github.com/kotlin-orm/ktorm/issues/517#issuecomment-1672431581

**Comment by yhsj0919** [comment]
改完之后还是同样的问题
```kotlin
//查询
                val tm = Orders.aliased("tm")
                val creator = tm.creatorId.referenceTable as Users
                val editor = tm.editorId.referenceTable as Users
                mysql(it.db())
                    .from(tm)
                    .leftJoin(creator, tm.creatorId eq creator.id)
                    .leftJoin(editor, tm.editorId eq editor.id)
                    .select()
```
```kotlin
 val creatorId = long("creator_id").references(Users) { it.creator }.bindTo { it.creatorId }
 val editorId = long("editor_id").references(Users) { it.editor }.bindTo { it.editorId }
```
```
java.lang.IllegalArgumentException: Confused column name, there are more than one column named 'id' in query: 

SELECT * 
FROM sys_sale_order tm 
LEFT JOIN sys_user _ref0 ON tm.creator_id = _ref0.id 
LEFT JOIN sys_user _ref1 ON tm.editor_id = _ref1.id 

	at org.ktorm.dsl.QueryRowSet.get(QueryRowSet.kt:77)
	at org.ktorm.schema.Table.retrieveColumn(Table.kt:138)
	at org.ktorm.schema.Table.doCreateEntity(Table.kt:131)
	at org.ktorm.schema.Table.retrieveColumn(Table.kt:149)
	at org.ktorm.schema.Table.doCreateEntity(Table.kt:131)
	at org.ktorm.schema.Table.doCreateEntity(Table.kt:49)
	at org.ktorm.schema.BaseTable.createEntity(BaseTable.kt:353)
	at org.ktorm.schema.BaseTable.createEntity$default(BaseTable.kt:352)
```
去掉一个左联 User 就可以正常填充
这里遇到的情况和#517不太一样，单个对象关联没问题，只是在关联两个相同的对象时出现

**Comment by vincentlauvlwj** [comment]
这一行

```kotlin
.select()
```

改成 

```kotlin
.select(tm.columns + creator.columns + editor.columns)
```

**Comment by yhsj0919** [comment]
可以了，谢谢
