### ISSUE TITLE
Multiple onConflict at bulkInsertOrUpdate

### ISSUE THREAD

**Issue by flben233** [kotlin-orm/ktorm#539]
I want to implement that each item has its onConflict value, so I use the code below: 
```
database.bulkInsertOrUpdate(VotePtTable) {
    for ((a, b) in map) {
        item {
            set(it.a, a)
            set(it.b, b)
        }
        onConflict {
            set(it.b, it.b+ b)
        }
    }
}
```
But I got this error: 

```
Caused by: org.postgresql.util.PSQLException: ERROR: multiple assignments to same column "b"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2712)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2400)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:367)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.ktorm.database.Database.executeUpdate(Database.kt:464)
	... 92 more
```
What's the right way to do this? Thanks a lot!

**Comment by vincentlauvlwj** [comment]
```kotlin
for ((a, b) in map) {
    database.insertOrUpdate(VotePtTable) {
        item {
            set(it.a, a)
            set(it.b, b)
        }
        onConflict {
            set(it.b, it.b+ b)
        }
    }
}
```
